# Generated by Django 5.2.3 on 2025-06-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYearStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HoldStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holds_placed', models.PositiveIntegerField()),
                ('holds_fulfilled', models.PositiveIntegerField()),
                ('holds_cko', models.PositiveIntegerField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_data.monthyearstat')),
            ],
        ),
        migrations.CreateModel(
            name='CirculationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circ_stat_type', models.CharField(choices=[('adult', 'Adult'), ('children', 'Children'), ('young_adult', 'Young Adult'), ('audiobook', 'Audiobook'), ('dvd', 'DVD'), ('video_game', 'Video Game'), ('magazine', 'Magazine'), ('lot', 'Library of Things'), ('local_use', 'Local Use'), ('ill', 'ILL')], max_length=50)),
                ('circ_value', models.PositiveIntegerField()),
                ('renewal_value', models.PositiveIntegerField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_data.monthyearstat')),
            ],
            options={
                'ordering': ['circ_stat_type'],
                'unique_together': {('month', 'circ_stat_type')},
            },
        ),
    ]
