# Generated by Django 5.2.3 on 2025-06-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('adult_cko', 'Adult Checkout'), ('children_cko', 'Children CKO'), ('young_adult_cko', 'Young Adult CKO'), ('audiobook_cko', 'Audiobook CKO'), ('dvd_cko', 'DVD CKO'), ('video_game_cko', 'Video Game CKO'), ('magazine_cko', 'Magazine CKO'), ('lot_cko', 'Library of Things CKO'), ('local_use_cko', 'Local Use CKO'), ('ill_cko', 'ILL CKO')], max_length=50)),
                ('month', models.DateField()),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-month', 'stat_type'],
                'unique_together': {('stat_type', 'month')},
            },
        ),
    ]
